### ISSUE TITLE
您好，请问为什么所有书籍导出的笔记部分都是空的呢？

### ISSUE THREAD

**Issue by TankardYegga** [sethyuan/chrome-weread-sync#1]
![image](https://github.com/sethyuan/chrome-weread-sync/assets/48079583/72e4bc0d-d391-4a40-bed8-59009443e237)

但是微信读书上，这些书的的确确是有笔记的。

是因为微信读书的会员限制吗？就是有些书当时免费给看了，后面变成会员了，可是这些书的笔记是可以直接通过微信的“导出笔记”复制下来的。

**Comment by sethyuan** [comment]
我还没有遇到过这种问题。可以试试将浏览器插件中的增量key清掉重新全量同步看看。

![image](https://github.com/sethyuan/chrome-weread-sync/assets/3410293/d70f9bcc-a0f2-478e-afe0-32ad2f5763e6)
